---

- name: Configure networks on OpenBSD
  when:
    - ansible_os_family == 'OpenBSD'
  block:
    - name: "Include install-{{ ansible_os_family }}.yml"
      include: "install-{{ ansible_os_family }}.yml"

    - name: "Create hostname.if {{ item['name'] }}"
      template:
        src: hostname.if.j2
        dest: "{{ netstart_config_dir }}/hostname.{{ item['name'] }}"
        mode: '0640'
      with_items: "{{ netstart_config }}"
      register: __netstart_result
      notify:
        - Restart netstart_service

    - name: Include flush_handlers.yml
      when:
        - netstart_force_flush_handlers
      include_tasks: flush_handlers.yml
